"""Source-owned alias observations with record grouping and temporal snapshots.

Identity declarations are authoritative source metadata, never generated by an
LLM. Name equality does not collapse stable IDs or certify real-world absence.
"""

from dataclasses import dataclass
from bisect import bisect_right
from types import MappingProxyType
from .integrity import canonical

from .types import EntityRef, ToolIdentity


@dataclass(frozen=True)
class IdentityDeclaration:
    tool: ToolIdentity
    namespace: str
    record_path: tuple[str, ...]
    id_field: str
    alias_fields: tuple[str, ...]
    authority_source: str
    full_alias_snapshot: bool = False
    id_type: str = 'string'

    def __post_init__(self):
        if not isinstance(self.tool, ToolIdentity) or not self.namespace or not self.authority_source:
            raise ValueError('exact tool identity and authoritative source required')
        if not self.id_field or not self.alias_fields or self.id_field in self.alias_fields:
            raise ValueError('distinct explicitly declared identity and alias fields required')
        if len(set(self.alias_fields)) != len(self.alias_fields) or type(self.full_alias_snapshot) is not bool:
            raise ValueError('unique alias fields and explicit snapshot premise required')
        if self.id_type not in {'string', 'integer'}:
            raise ValueError('explicit stable ID type required')
        if (type(self.record_path) is not tuple or type(self.alias_fields) is not tuple
            or any(not isinstance(part, str) or not part for part in self.record_path)
            or any(not isinstance(field, str) or not field for field in self.alias_fields)):
            raise ValueError('immutable declared source paths/fields required')


@dataclass(frozen=True)
class AliasObservation:
    entity: EntityRef
    aliases: tuple[str, ...]
    event_id: str
    index: int
    record_path: tuple[str, ...]
    authority_source: str
    full_snapshot: bool


@dataclass(frozen=True)
class IdentityRecord:
    entity: EntityRef
    event_id: str
    index: int
    record_path: tuple[str, ...]
    record_json: str


@dataclass(frozen=True)
class AliasCandidates:
    entities: tuple[EntityRef, ...]
    observations: tuple[AliasObservation, ...]
    searched_source_complete: bool
    unresolved_terms: tuple[str, ...]
    searched_observation_count: int = 0
    semantics: str = 'observed identity candidates at/before source index; not current-state or absence proof'


def records_at(payload, path):
    """'*' traverses explicitly declared collections, not arbitrary nesting."""
    rows = [(payload, ())]
    for part in path:
        expanded = []
        for value, actual_path in rows:
            if part == '*' and isinstance(value, list):
                expanded.extend((item, (*actual_path, str(index))) for index, item in enumerate(value))
            elif isinstance(value, dict) and part in value:
                expanded.append((value[part], (*actual_path, part)))
        rows = expanded
    return rows


class IdentityAliasIndex:
    def __init__(self, ledger, declarations):
        declarations = tuple(declarations)
        if len({item.tool for item in declarations}) != len(declarations):
            raise ValueError('duplicate tool declarations require explicit source resolution')
        identity_types = {}
        for declaration in declarations:
            key = declaration.namespace, declaration.id_field
            if key in identity_types and identity_types[key] != declaration.id_type:
                raise ValueError('conflicting stable ID types in one namespace')
            identity_types[key] = declaration.id_type
        self.ledger, self.declarations = ledger, declarations
        by_tool = {item.tool: item for item in declarations}
        observations, unresolved, identity_records = [], [], []
        for event in ledger.events:
            if event.kind != 'result':
                continue  # call arguments / user or assistant claims are not identity observations
            if event.actor != 'tool':
                unresolved.append((event.index, 'result_identity_role_untrusted'))
                continue
            declaration = by_tool.get(event.tool)
            if declaration is None:
                unresolved.append((event.index, 'result_identity_semantics_undeclared'))
                continue
            if event.payload_json is None or event.pairing_issue:
                unresolved.append((event.index, 'result_identity_source_incomplete'))
                continue
            rows = records_at(event.payload, declaration.record_path)
            if not rows:
                unresolved.append((event.index, 'declared_record_path_missing'))
            for row, path in rows:
                id_type = str if declaration.id_type == 'string' else int
                if not isinstance(row, dict) or type(row.get(declaration.id_field)) is not id_type:
                    unresolved.append((event.index, 'declared_record_identity_missing'))
                    continue
                identity = str(row[declaration.id_field])
                if not identity:
                    unresolved.append((event.index, 'declared_record_identity_missing'))
                    continue
                entity = EntityRef(declaration.id_field, identity, declaration.namespace)
                identity_records.append(IdentityRecord(entity, event.event_id, event.index, path,
                    canonical(row).decode('utf-8')))
                aliases = []
                full = declaration.full_alias_snapshot
                for field in declaration.alias_fields:
                    if field not in row:
                        unresolved.append((event.index, 'declared_alias_field_missing'))
                        full = False
                        continue
                    value = row[field]
                    values = value if isinstance(value, list) else [value]
                    if any(not isinstance(alias, str) or not alias for alias in values):
                        unresolved.append((event.index, 'declared_alias_value_unknown'))
                        full = False
                    aliases.extend(alias for alias in values if isinstance(alias, str) and alias)
                observations.append(AliasObservation(entity,
                    tuple(dict.fromkeys(aliases)), event.event_id, event.index, path,
                    declaration.authority_source, full))
        self.observations = tuple(observations)
        self.source_issues = tuple(dict.fromkeys(unresolved))
        records_by_key = {}
        for record in identity_records:
            records_by_key.setdefault((record.entity, record.event_id), []).append(record)
        self.records_by_entity_event = MappingProxyType({key: tuple(rows) for key, rows in records_by_key.items()})
        malformed_indexes = {position for position, code in self.source_issues
            if code in {'declared_record_identity_missing', 'declared_record_path_missing'}}
        self.malformed_record_event_ids = frozenset(event.event_id for event in ledger.events if event.index in malformed_indexes)
        by_alias, snapshot_times = {}, {}
        for observation in self.observations:
            for alias in observation.aliases:
                by_alias.setdefault(alias, []).append(observation)
            if observation.full_snapshot:
                snapshot_times.setdefault(observation.entity, set()).add(observation.index)
        self.by_alias = {alias: tuple(sorted(rows, key=lambda row: row.index)) for alias, rows in by_alias.items()}
        self.alias_times = {alias: tuple(row.index for row in rows) for alias, rows in self.by_alias.items()}
        self.snapshot_times = {entity: tuple(sorted(times)) for entity, times in snapshot_times.items()}

    def resolve(self, alias, *, before_index=None, namespace=None):
        if not isinstance(alias, str) or not alias:
            raise ValueError('explicit nonempty name required')
        if before_index is None:
            before_index = len(self.ledger.events) - 1
        if type(before_index) is not int or not 0 <= before_index < len(self.ledger.events):
            return AliasCandidates((), (), False, ('identity_time_unbound',))
        alias_rows = self.by_alias.get(alias, ())
        alias_rows = alias_rows[:bisect_right(self.alias_times.get(alias, ()), before_index)]
        matching = []
        latest_snapshots = {}
        for observation in alias_rows:
            if namespace is not None and observation.entity.namespace != namespace:
                continue
            if observation.entity not in latest_snapshots:
                times = self.snapshot_times.get(observation.entity, ())
                position = bisect_right(times, before_index)
                latest_snapshots[observation.entity] = times[position - 1] if position else -1
            # Same-index conflicting snapshots are preserved, not last-wins.
            if observation.index >= latest_snapshots[observation.entity]:
                matching.append(observation)
        matching = tuple(matching)
        entities = tuple(sorted({item.entity for item in matching}, key=lambda ref: (ref.namespace, ref.key, ref.value)))
        source_issues = tuple(dict.fromkeys(code for index, code in self.source_issues if index <= before_index))
        unresolved = list(source_issues)
        if not matching:
            unresolved.append('name_not_observed_not_absent')
        if len(entities) > 1:
            unresolved.append('name_identity_ambiguous')
        complete = self.ledger.history_complete and bool(self.ledger.completeness_basis) and not source_issues
        return AliasCandidates(entities, matching, complete, tuple(dict.fromkeys(unresolved)), len(alias_rows))
