"""Final Policy cycle - fresh final holdout corpus, entries part 2.

Part 2 cohorts: scope (together/separate), one_of_all_of (condition
coordination), exception_attachment, condition_attachment, temporal,
provenance, multi_axis, nl_prose_stress.
"""
from __future__ import annotations

ENTRIES_PART2: list[tuple] = [
    # --------------------------------------------------------------- scope (9)
    ("scope", "controlled", [
        ("sc01", "Glaze dust and kiln wash must never be swept with the same broom.",
         "RULESET(RULE(PROHIBIT, TOGETHER(:action:sweep_glaze_dust, :action:sweep_kiln_wash)))",
         {"action:sweep_glaze_dust": "Glaze dust", "action:sweep_kiln_wash": "kiln wash"},
         [("MODAL", "PROHIBIT", "never")], [],
         ["action:sweep_clay_dust"]),
        ("sc02", "You must stamp the workcard and the parts sheet as one bundle.",
         "RULESET(RULE(REQUIRE, TOGETHER(:action:stamp_the_workcard, :action:stamp_the_parts_sheet)))",
         {"action:stamp_the_workcard": "stamp the workcard", "action:stamp_the_parts_sheet": "the parts sheet"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:stamp_the_invoice"]),
        ("sc03", "Ride operators may load the gondola and check the harnesses as separate tasks.",
         "RULESET(RULE(PERMIT, SEPARATE(:action:load_the_gondola, :action:check_the_harnesses)))",
         {"action:load_the_gondola": "load the gondola", "action:check_the_harnesses": "check the harnesses"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:load_the_turntable"]),
        ("sc04", "The honey wine and the cider must be fermented in separate vessels.",
         "RULESET(RULE(REQUIRE, SEPARATE(:action:ferment_honey_wine, :action:ferment_cider)))",
         {"action:ferment_honey_wine": "The honey wine", "action:ferment_cider": "the cider"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:ferment_mead"]),
        ("sc05", "The moth samples and the bat pellets must be frozen in one shared box.",
         "RULESET(RULE(REQUIRE, TOGETHER(:action:freeze_moth_samples, :action:freeze_bat_pellets)))",
         {"action:freeze_moth_samples": "The moth samples", "action:freeze_bat_pellets": "the bat pellets"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:freeze_beetle_traps"]),
        ("sc06", "Visitors may photograph the seal pool and film the penguin walk as independent activities.",
         "RULESET(RULE(PERMIT, SEPARATE(:action:photograph_the_seal_pool, :action:film_the_penguin_walk)))",
         {"action:photograph_the_seal_pool": "photograph the seal pool", "action:film_the_penguin_walk": "film the penguin walk"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:film_the_seal_pool"]),
        ("sc07", "The floor slabs and the bench tops must be lifted with the same gantry run.",
         "RULESET(RULE(REQUIRE, TOGETHER(:action:lift_the_floor_slabs, :action:lift_the_bench_tops)))",
         {"action:lift_the_floor_slabs": "The floor slabs", "action:lift_the_bench_tops": "the bench tops"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:lift_the_roof_panels"]),
        ("sc08", "Stewards must not weigh the fleeces and the skins on the same scale.",
         "RULESET(RULE(PROHIBIT, TOGETHER(:action:weigh_the_fleeces, :action:weigh_the_skins)))",
         {"action:weigh_the_fleeces": "weigh the fleeces", "action:weigh_the_skins": "the skins"},
         [("MODAL", "PROHIBIT", "must not")], [],
         ["action:weigh_the_tack_box"]),
        ("sc09", "You may varnish the hull and the spars as two separate jobs.",
         "RULESET(RULE(PERMIT, SEPARATE(:action:varnish_the_hull, :action:varnish_the_spars)))",
         {"action:varnish_the_hull": "varnish the hull", "action:varnish_the_spars": "the spars"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:varnish_the_oars"]),
    ]),
    # ------------------------------------------------- one_of_all_of (4)
    ("one_of_all_of", "controlled", [
        ("oa01", "Guests may hire a rowboat if they show either a harbour pass or a photo identity card.",
         "RULESET(RULE(PERMIT, :action:hire_a_rowboat, WHEN(OR(:state:harbour_pass_shown, :state:photo_id_shown))))",
         {"action:hire_a_rowboat": "hire a rowboat",
          "state:harbour_pass_shown": "a harbour pass",
          "state:photo_id_shown": "a photo identity card"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "if")], [],
         ["state:credit_card_shown", "action:hire_a_canoe"]),
        ("oa02", "The seed vault may be opened only when both the curator and the duty warden are present.",
         "RULESET(RULE(PERMIT, :action:open_the_seed_vault, ONLY_WHEN(AND(:state:curator_present, :state:duty_warden_present))))",
         {"action:open_the_seed_vault": "The seed vault",
          "state:curator_present": "the curator", "state:duty_warden_present": "the duty warden"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "ONLY_IF", "only when")], [],
         ["state:gardener_present", "action:open_the_polytunnel"]),
        ("oa03", "Trainees may use the rip saw when the guard is fitted and the extraction is running.",
         "RULESET(RULE(PERMIT, :action:use_the_rip_saw, WHEN(AND(:state:guard_fitted, :state:extraction_running))))",
         {"action:use_the_rip_saw": "use the rip saw",
          "state:guard_fitted": "the guard is fitted",
          "state:extraction_running": "the extraction is running"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "when")], [],
         ["state:blade_sharp", "action:use_the_band_saw"]),
        ("oa04", "Pupils may sit the practical if they hold either a signed logbook or a supervisor's note.",
         "RULESET(RULE(PERMIT, :action:sit_the_practical, WHEN(OR(:state:signed_logbook_held, :state:supervisor_note_held))))",
         {"action:sit_the_practical": "sit the practical",
          "state:signed_logbook_held": "a signed logbook",
          "state:supervisor_note_held": "a supervisor's note"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "if")], [],
         ["state:medical_note_held", "action:sit_the_written"]),
    ]),
    # ----------------------------------------------- exception_attachment (5)
    ("exception_attachment", "controlled", [
        ("xa01", "Except during the winter haul-out, members must wear deck shoes on the pontoons, and life jackets have to be worn on the water.",
         "RULESET(RULE(REQUIRE, :action:wear_deck_shoes, EXCEPT(:state:winter_haulout)), RULE(REQUIRE, :action:wear_life_jackets))",
         {"action:wear_deck_shoes": "wear deck shoes on the pontoons",
          "state:winter_haulout": "during the winter haul-out",
          "action:wear_life_jackets": "life jackets"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "REQUIRE", "have to"),
          ("RELATION", "UNLESS", "Except during")], [],
         ["action:wear_gloves", "state:pontoons_flooded"]),
        ("xa02", "Unless the duty manager signs the sheet, instructors may not lead the gorge walk, and the sea traverse is barred entirely.",
         "RULESET(RULE(PROHIBIT, :action:lead_the_gorge_walk, EXCEPT(:state:duty_manager_signed)), RULE(PROHIBIT, :action:lead_the_sea_traverse))",
         {"action:lead_the_gorge_walk": "lead the gorge walk",
          "state:duty_manager_signed": "the duty manager signs the sheet",
          "action:lead_the_sea_traverse": "the sea traverse"},
         [("MODAL", "PROHIBIT", "may not"), ("MODAL", "PROHIBIT", "barred"),
          ("RELATION", "UNLESS", "Unless")], [],
         ["action:lead_the_ridge_hike", "state:sheet_missing"]),
        ("xa03", "Save on closed days, keepers must bag the falcon scraps, and the weighing has to be logged.",
         "RULESET(RULE(REQUIRE, :action:bag_the_falcon_scraps, EXCEPT(:state:centre_closed_day)), RULE(REQUIRE, :action:log_the_weighing))",
         {"action:bag_the_falcon_scraps": "bag the falcon scraps",
          "state:centre_closed_day": "on closed days",
          "action:log_the_weighing": "the weighing"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "REQUIRE", "has to"),
          ("RELATION", "UNLESS", "Save on")], [],
         ["action:bag_the_owl_scraps", "state:scale_broken"]),
        ("xa04", "Apart from during feeding demonstrations, visitors may film inside the hatchery, and the larval shed can be filmed too.",
         "RULESET(RULE(PERMIT, :action:film_inside_the_hatchery, EXCEPT(:state:feeding_demonstration)), RULE(PERMIT, :action:film_inside_the_larval_shed))",
         {"action:film_inside_the_hatchery": "film inside the hatchery",
          "state:feeding_demonstration": "during feeding demonstrations",
          "action:film_inside_the_larval_shed": "the larval shed"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PERMIT", "can"),
          ("RELATION", "UNLESS", "Apart from during")], [],
         ["action:film_inside_the_visitors_centre", "state:demo_finished"]),
        ("xa05", "Except on public holidays, duty hands must chalk the boards, and the clocks are to be reset daily.",
         "RULESET(RULE(REQUIRE, :action:chalk_the_boards, EXCEPT(:state:public_holiday)), RULE(REQUIRE, :action:reset_the_clocks))",
         {"action:chalk_the_boards": "chalk the boards",
          "state:public_holiday": "on public holidays",
          "action:reset_the_clocks": "the clocks"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "REQUIRE", "are to be"),
          ("RELATION", "UNLESS", "Except on")], [],
         ["action:chalk_the_floors", "state:clocks_synced"]),
    ]),
    # ----------------------------------------------- condition_attachment (5)
    ("condition_attachment", "controlled", [
        ("ca01", "If the night baker is on site, dough mixers may run the spiral arm, and the divider hopper can always be run.",
         "RULESET(RULE(PERMIT, :action:run_the_spiral_arm, WHEN(:state:night_baker_on_site)), RULE(PERMIT, :action:run_the_divider_hopper))",
         {"action:run_the_spiral_arm": "run the spiral arm",
          "state:night_baker_on_site": "the night baker is on site",
          "action:run_the_divider_hopper": "the divider hopper"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PERMIT", "can"),
          ("RELATION", "IF", "If")], [],
         ["action:run_the_prover", "state:day_baker_on_site"]),
        ("ca02", "When the yard opens, grooms must muck the loose boxes, and the tack aisle is to be swept daily.",
         "RULESET(RULE(REQUIRE, :action:muck_the_loose_boxes, WHEN(:state:yard_open)), RULE(REQUIRE, :action:sweep_the_tack_aisle))",
         {"action:muck_the_loose_boxes": "muck the loose boxes",
          "state:yard_open": "the yard opens",
          "action:sweep_the_tack_aisle": "the tack aisle"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "REQUIRE", "is to be"),
          ("RELATION", "IF", "When")], [],
         ["action:muck_the_stalls", "state:yard_closed"]),
        ("ca03", "If the shop till is staffed, volunteers may refill the seed dispensers, and the trolley can be borrowed freely.",
         "RULESET(RULE(PERMIT, :action:refill_the_seed_dispensers, WHEN(:state:shop_till_staffed)), RULE(PERMIT, :action:borrow_the_trolley))",
         {"action:refill_the_seed_dispensers": "refill the seed dispensers",
          "state:shop_till_staffed": "the shop till is staffed",
          "action:borrow_the_trolley": "the trolley"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PERMIT", "can"),
          ("RELATION", "IF", "If")], [],
         ["action:refill_the_bird_feeders", "state:trolley_in_use"]),
        ("ca04", "When the base station is staffed, wardens must log the sightings, and the radios have to be charged nightly.",
         "RULESET(RULE(REQUIRE, :action:log_the_sightings, WHEN(:state:base_station_staffed)), RULE(REQUIRE, :action:charge_the_radios))",
         {"action:log_the_sightings": "log the sightings",
          "state:base_station_staffed": "the base station is staffed",
          "action:charge_the_radios": "the radios"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "REQUIRE", "have to"),
          ("RELATION", "IF", "When")], [],
         ["action:log_the_weather", "state:radios_charged"]),
        ("ca05", "If the technician countersigns, students may fire the gas kiln, and the salt glaze room can be opened as well.",
         "RULESET(RULE(PERMIT, :action:fire_the_gas_kiln, WHEN(:state:technician_countersigned)), RULE(PERMIT, :action:open_the_salt_glaze_room))",
         {"action:fire_the_gas_kiln": "fire the gas kiln",
          "state:technician_countersigned": "the technician countersigns",
          "action:open_the_salt_glaze_room": "the salt glaze room"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PERMIT", "can"),
          ("RELATION", "IF", "If")], [],
         ["action:fire_the_wood_kiln", "state:technician_absent"]),
    ]),
    # ------------------------------------------------------------- temporal (4)
    ("temporal", "controlled", [
        ("t01", "Once the kiln reaches cone six, students must stop stoking.",
         "RULESET(RULE(REQUIRE, :action:stop_stoking, AFTER(:event:kiln_reaches_cone_six)))",
         {"action:stop_stoking": "stop stoking", "event:kiln_reaches_cone_six": "the kiln reaches cone six"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "AFTER", "Once")], [],
         ["event:kiln_drops_to_cone_five", "action:resume_stoking"]),
        ("t02", "Punt operators must brief their passengers before every trip leaves the mooring.",
         "RULESET(RULE(REQUIRE, :action:brief_the_passengers, BEFORE(:event:trip_leaves_mooring)))",
         {"action:brief_the_passengers": "brief their passengers",
          "event:trip_leaves_mooring": "every trip leaves the mooring"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "BEFORE", "before")], [],
         ["event:trip_returns", "action:thank_the_passengers"]),
        ("t03", "Candidates may open the result envelopes after the adjutant calls the roll.",
         "RULESET(RULE(PERMIT, :action:open_the_result_envelopes, AFTER(:event:adjutant_calls_roll)))",
         {"action:open_the_result_envelopes": "open the result envelopes",
          "event:adjutant_calls_roll": "the adjutant calls the roll"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "AFTER", "after")], [],
         ["event:adjutant_leaves", "action:open_the_despatch_box"]),
        ("t04", "The press operators must thread the new reels before the edition meeting starts.",
         "RULESET(RULE(REQUIRE, :action:thread_the_new_reels, BEFORE(:event:edition_meeting_starts)))",
         {"action:thread_the_new_reels": "thread the new reels",
          "event:edition_meeting_starts": "the edition meeting starts"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "BEFORE", "before")], [],
         ["event:edition_meeting_ends", "action:remove_the_old_reels"]),
    ]),
    # ----------------------------------------------------------- provenance (3)
    ("provenance", "controlled", [
        ("p01", "Fuel claims must be supported by till receipts issued by the forecourt itself.",
         "RULESET(RULE(REQUIRE, :action:submit_fuel_claims, PROVENANCE(:evidence:forecourt_till_receipts)))",
         {"action:submit_fuel_claims": "Fuel claims",
          "evidence:forecourt_till_receipts": "till receipts issued by the forecourt"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "ONLY_IF", "supported by")], [],
         ["evidence:handwritten_notes", "action:submit_tool_claims"]),
        ("p02", "Herbarium accessions may be vouched only by sheets stamped at the regional bureau.",
         "RULESET(RULE(PERMIT, :action:voucher_herbarium_accessions, PROVENANCE(:evidence:regional_bureau_sheets)))",
         {"action:voucher_herbarium_accessions": "Herbarium accessions",
          "evidence:regional_bureau_sheets": "sheets stamped at the regional bureau"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "ONLY_IF", "only by")], [],
         ["evidence:field_notebook", "action:label_herbarium_accessions"]),
        ("p03", "Tide readings may be logged solely from the gauge printouts.",
         "RULESET(RULE(PERMIT, :action:log_tide_readings, PROVENANCE(:evidence:gauge_printouts)))",
         {"action:log_tide_readings": "Tide readings",
          "evidence:gauge_printouts": "the gauge printouts"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "ONLY_IF", "solely from")], [],
         ["evidence:phone_photos", "action:log_wind_readings"]),
    ]),
    # ----------------------------------------------------------- multi_axis (8)
    ("multi_axis", "controlled", [
        ("x01", "While the observatory floor is wet, astronomers may use the catwalk when harnesses are on.",
         "RULESET(RULE(PERMIT, :action:use_the_catwalk, WHEN(AND(:state:observatory_floor_wet, :state:harnesses_on))))",
         {"action:use_the_catwalk": "use the catwalk",
          "state:observatory_floor_wet": "the observatory floor is wet",
          "state:harnesses_on": "harnesses are on"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "While")], [],
         ["state:floor_dry", "action:use_the_stairs"]),
        ("x02", "If the fruit press is hired and the farmer does not collect the crates, helpers must wash the crates.",
         "RULESET(RULE(REQUIRE, :action:wash_the_crates, WHEN(AND(:state:fruit_press_hired, NOT(:state:farmer_collects_crates)))))",
         {"action:wash_the_crates": "wash the crates",
          "state:fruit_press_hired": "the fruit press is hired",
          "state:farmer_collects_crates": "the farmer does not collect the crates"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "If")], [],
         ["state:cider_mill_hired", "action:stack_the_crates"]),
        ("x03", "If the loft hatch is open, apprentices may fetch the ladders and the torches, but never the scaffolding.",
         "RULESET(RULE(PERMIT, :action:fetch_the_ladders, WHEN(:state:loft_hatch_open)), RULE(PERMIT, :action:fetch_the_torches, WHEN(:state:loft_hatch_open)), RULE(PROHIBIT, :action:fetch_the_scaffolding, WHEN(:state:loft_hatch_open)))",
         {"action:fetch_the_ladders": "fetch the ladders",
          "action:fetch_the_torches": "the torches",
          "action:fetch_the_scaffolding": "the scaffolding",
          "state:loft_hatch_open": "the loft hatch is open"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PROHIBIT", "never"),
          ("RELATION", "IF", "If")], [],
         ["state:loft_hatch_closed", "action:fetch_the_ropes"]),
        ("x04", "Ski patrollers must carry flares on the ridge and may launch the drone only when the wind drops.",
         "RULESET(RULE(REQUIRE, :action:carry_flares_on_ridge), RULE(PERMIT, :action:launch_the_drone, ONLY_WHEN(:state:wind_dropped)))",
         {"action:carry_flares_on_ridge": "carry flares on the ridge",
          "action:launch_the_drone": "launch the drone",
          "state:wind_dropped": "the wind drops"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may"),
          ("RELATION", "ONLY_IF", "only when")], [],
         ["action:carry_flares_in_hut", "state:wind_rising"]),
        ("x05", "When the tasting bar is unstaffed, visitors may not sample the casks, and guides must lock the cellar door.",
         "RULESET(RULE(PROHIBIT, :action:sample_the_casks, WHEN(NOT(:state:tasting_bar_staffed))), RULE(REQUIRE, :action:lock_the_cellar_door, WHEN(NOT(:state:tasting_bar_staffed))))",
         {"action:sample_the_casks": "sample the casks",
          "state:tasting_bar_staffed": "the tasting bar is unstaffed",
          "action:lock_the_cellar_door": "lock the cellar door"},
         [("MODAL", "PROHIBIT", "may not"), ("MODAL", "REQUIRE", "must"),
          ("RELATION", "IF", "When")], [],
         ["state:bar_closed", "action:sample_the_bottles"]),
        ("x06", "Only beekeepers may open the hive screens, and the entrance must be smoked before the first frame comes out.",
         "RULESET(RULE(PERMIT, :action:open_the_hive_screens, ONLY_ACTOR(:actor:beekeeper)), RULE(REQUIRE, :action:smoke_the_entrance, BEFORE(:event:first_frame_comes_out)))",
         {"action:open_the_hive_screens": "open the hive screens",
          "actor:beekeeper": "beekeepers",
          "action:smoke_the_entrance": "smoked",
          "event:first_frame_comes_out": "the first frame comes out"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must"),
          ("RELATION", "ONLY_IF", "Only"), ("RELATION", "BEFORE", "before")], [],
         ["actor:guests", "action:open_the_hive_lids"]),
        ("x07", "When the ferry lamp shows green, deckhands may cast off, unless the log shows an open defect.",
         "RULESET(RULE(PERMIT, :action:cast_off, WHEN(:state:ferry_lamp_green), EXCEPT(:state:log_shows_open_defect)))",
         {"action:cast_off": "cast off",
          "state:ferry_lamp_green": "the ferry lamp shows green",
          "state:log_shows_open_defect": "the log shows an open defect"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "When"),
          ("RELATION", "UNLESS", "unless")], [],
         ["state:ferry_lamp_red", "action:tie_up"]),
        ("x08", "Bakers must wear oven gloves at the muffle, and only the shift lead may adjust the dampers.",
         "RULESET(RULE(REQUIRE, :action:wear_oven_gloves_at_muffle), RULE(PERMIT, :action:adjust_the_dampers, ONLY_ACTOR(:actor:shift_lead)))",
         {"action:wear_oven_gloves_at_muffle": "wear oven gloves at the muffle",
          "action:adjust_the_dampers": "adjust the dampers",
          "actor:shift_lead": "the shift lead"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may"),
          ("RELATION", "ONLY_IF", "only the")], [],
         ["action:wear_oven_gloves_at_sink", "actor:apprentice"]),
    ]),
    # ------------------------------------------------------ nl_prose_stress (7)
    ("nl_prose_stress", "natural", [
        ("np01", "Because the ravine path gets slippery after rain, walkers who have not checked the noticeboard may not attempt the descent, though the upper meadow loop stays open to everyone.",
         "RULESET(RULE(PROHIBIT, :action:attempt_the_descent, WHEN(NOT(:state:noticeboard_checked))))",
         {"action:attempt_the_descent": "attempt the descent",
          "state:noticeboard_checked": "have not checked the noticeboard"},
         [("MODAL", "PROHIBIT", "may not"), ("RELATION", "IF", "Because")],
         [("state:upper_meadow_loop_open", "the upper meadow loop stays open"),
          ("state:ravine_path_slippery", "the ravine path gets slippery")],
         ["action:hike_the_ridge", "state:noticeboard_missing"]),
        ("np02", "Although the print studio welcomes experimentation, solvent-based inks are off limits unless a technician has signed the session sheet, and even then the drying cabinet needs a watcher.",
         "RULESET(RULE(PROHIBIT, :action:use_solvent_based_inks, EXCEPT(:state:technician_signed_sheet)), RULE(REQUIRE, :action:watch_the_drying_cabinet, WHEN(:state:technician_signed_sheet)))",
         {"action:use_solvent_based_inks": "solvent-based inks",
          "state:technician_signed_sheet": "a technician has signed the session sheet",
          "action:watch_the_drying_cabinet": "the drying cabinet"},
         [("MODAL", "PROHIBIT", "off limits"), ("MODAL", "REQUIRE", "needs"),
          ("RELATION", "UNLESS", "unless"), ("RELATION", "IF", "then")], [],
         ["action:use_water_based_inks", "state:sheet_unsigned"]),
        ("np03", "The warden is happy for campers to gather deadwood anywhere east of the stream, provided nothing green is cut and the fire pit is the only place it is burned.",
         "RULESET(RULE(PERMIT, :action:gather_deadwood_east_of_stream, WHEN(AND(NOT(:state:green_cut), :state:burning_only_at_fire_pit))))",
         {"action:gather_deadwood_east_of_stream": "gather deadwood anywhere east of the stream",
          "state:green_cut": "nothing green is cut",
          "state:burning_only_at_fire_pit": "the fire pit is the only place it is burned"},
         [("MODAL", "PERMIT", "happy for"), ("RELATION", "IF", "provided")], [],
         ["action:gather_greenwood", "state:stream_flooded"]),
        ("np04", "While the refit shed is noisy at the best of times, volunteers may still operate the band saw when ear defenders are worn and the dust extractor hums, but never during the lunchtime inspections.",
         "RULESET(RULE(PERMIT, :action:operate_the_band_saw, WHEN(AND(:state:ear_defenders_worn, :state:dust_extractor_humming)), EXCEPT(:state:lunchtime_inspection)))",
         {"action:operate_the_band_saw": "operate the band saw",
          "state:ear_defenders_worn": "ear defenders are worn",
          "state:dust_extractor_humming": "the dust extractor hums",
          "state:lunchtime_inspection": "during the lunchtime inspections"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "when"),
          ("RELATION", "UNLESS", "but never during")], [],
         ["action:operate_the_bench_grinder", "state:defenders_off"]),
        ("np05", "Ferry crew should note that the vehicle deck stays closed whenever sea state reaches five, even though foot passengers keep using the side gangway throughout.",
         "RULESET(RULE(PROHIBIT, :action:use_the_vehicle_deck, WHEN(:state:sea_state_five)))",
         {"action:use_the_vehicle_deck": "the vehicle deck",
          "state:sea_state_five": "sea state reaches five"},
         [("MODAL", "PROHIBIT", "stays closed"), ("RELATION", "IF", "whenever")],
         [("state:foot_passengers_use_side_gangway", "foot passengers keep using the side gangway")],
         ["action:use_the_car_deck_lift", "state:sea_state_three"]),
        ("np06", "Even if the tide tables look forgiving, diggers must check with the harbour office before raking the cockle beds, and afterwards they are welcome to sell their catch at the morning stall.",
         "RULESET(RULE(REQUIRE, :action:check_with_harbour_office, BEFORE(:event:cockle_beds_raked)), RULE(PERMIT, :action:sell_the_catch, AFTER(:event:cockle_beds_raked)))",
         {"action:check_with_harbour_office": "check with the harbour office",
          "event:cockle_beds_raked": "raking the cockle beds",
          "action:sell_the_catch": "sell their catch"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "welcome to"),
          ("RELATION", "BEFORE", "before"), ("RELATION", "AFTER", "afterwards")], [],
         ["event:tide_tables_checked", "action:sell_the_gear"]),
        ("np07", "Museum guides may open the cabinet drawers for visitors once the conservator has logged the humidity, though the pearl case in the west wing stays locked no matter what.",
         "RULESET(RULE(PERMIT, :action:open_the_cabinet_drawers, AFTER(:event:conservator_logs_humidity)), RULE(PROHIBIT, :action:open_the_pearl_case))",
         {"action:open_the_cabinet_drawers": "open the cabinet drawers",
          "event:conservator_logs_humidity": "the conservator has logged the humidity",
          "action:open_the_pearl_case": "the pearl case in the west wing"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PROHIBIT", "stays locked"),
          ("RELATION", "AFTER", "once")], [],
         ["event:humidity_logged_twice", "action:open_the_coin_case"]),
    ]),
]
