"""Final Policy cycle - fresh final holdout corpus, entries part 1.

100 gold-by-construction cases in completely fresh domains, authored for the
final architecture-selection holdout (user sections 40-45).  Entry format is
the shared GRS builder's: (key, text, gold_dsl, fact_spans, markers, inert,
distractors).  Gold DSL uses :kind:atom placeholders; spans are exact unique
substrings; markers exactly cover the gold's modality/relation evidence.

Part 1 cohorts: simple_flat, empty_gold_control, modality, condition,
exception, negation, multiclause, per_clause_modality, per_clause_actor.
"""
from __future__ import annotations

ENTRIES_PART1: list[tuple] = [
    # ------------------------------------------------------- simple_flat (11)
    ("simple_flat", "controlled", [
        ("sf01", "Patrollers must carry an avalanche transceiver on every patrol.",
         "RULESET(RULE(REQUIRE, :action:carry_avalanche_transceiver))",
         {"action:carry_avalanche_transceiver": "carry an avalanche transceiver"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:carry_a_radio", "state:patrol_cancelled"]),
        ("sf02", "Ski lift riders may stow overnight bags in the front basket.",
         "RULESET(RULE(PERMIT, :action:stow_overnight_bags_in_front_basket))",
         {"action:stow_overnight_bags_in_front_basket": "stow overnight bags in the front basket"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:stow_bags_on_seat", "state:basket_full"]),
        ("sf03", "Glasshouse visitors are barred from picking the orchid blooms.",
         "RULESET(RULE(PROHIBIT, :action:pick_the_orchid_blooms))",
         {"action:pick_the_orchid_blooms": "picking the orchid blooms"},
         [("MODAL", "PROHIBIT", "barred from")], [],
         ["action:photograph_the_orchids", "action:water_the_orchids"]),
        ("sf04", "Letterpress apprentices must oil the platen every evening.",
         "RULESET(RULE(REQUIRE, :action:oil_the_platen))",
         {"action:oil_the_platen": "oil the platen"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:clean_the_rollers", "state:platen_warm"]),
        ("sf05", "Ferry passengers may watch the ramp from the viewing rail.",
         "RULESET(RULE(PERMIT, :action:watch_the_ramp_from_viewing_rail))",
         {"action:watch_the_ramp_from_viewing_rail": "watch the ramp from the viewing rail"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:stand_on_the_ramp", "state:ramp_raised"]),
        ("sf06", "Bat surveyors are forbidden from shining white torches near the roost entrance.",
         "RULESET(RULE(PROHIBIT, :action:shine_white_torches_near_roost))",
         {"action:shine_white_torches_near_roost": "shining white torches near the roost entrance"},
         [("MODAL", "PROHIBIT", "forbidden from")], [],
         ["action:use_red_torch", "state:roost_occupied"]),
        ("sf07", "Turbine hall technicians must sign the isolation register.",
         "RULESET(RULE(REQUIRE, :action:sign_the_isolation_register))",
         {"action:sign_the_isolation_register": "sign the isolation register"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:sign_the_visitor_book", "state:register_complete"]),
        ("sf08", "Cheese dairy guests may sample the morning curd.",
         "RULESET(RULE(PERMIT, :action:sample_the_morning_curd))",
         {"action:sample_the_morning_curd": "sample the morning curd"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:sample_the_evening_curd", "state:curd_resting"]),
        ("sf09", "Planetarium lecturers must dim the house lights for every show.",
         "RULESET(RULE(REQUIRE, :action:dim_the_house_lights))",
         {"action:dim_the_house_lights": "dim the house lights"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:raise_the_screen", "state:projector_idle"]),
        ("sf10", "Dojo members are banned from sparring without gum shields.",
         "RULESET(RULE(PROHIBIT, :action:sparring_without_gum_shields))",
         {"action:sparring_without_gum_shields": "sparring without gum shields"},
         [("MODAL", "PROHIBIT", "banned from")], [],
         ["action:sparring_without_gloves", "state:gum_shield_checked"]),
        ("sf11", "Campsite wardens must log every arriving pitch.",
         "RULESET(RULE(REQUIRE, :action:log_every_arriving_pitch))",
         {"action:log_every_arriving_pitch": "log every arriving pitch"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:log_departing_pitch", "state:pitch_register_open"]),
    ]),
    # -------------------------------------------------- empty_gold_control (1)
    ("empty_gold_control", "controlled", [
        ("z01", "The tram museum keeps its fleet of open-top cars in the shed, and the souvenir counter opens at ten each morning.",
         "RULESET()", {},
         [], [("action:keep_open_top_cars_in_shed", "keeps its fleet of open-top cars in the shed"),
              ("state:souvenir_counter_opens_at_ten", "the souvenir counter opens at ten")],
         ["action:enter_the_shed", "action:buy_a_souvenir"]),
    ]),
    # ----------------------------------------------------------- modality (6)
    ("modality", "controlled", [
        ("m01", "Lock keepers may drain the paddle culvert at their discretion.",
         "RULESET(RULE(PERMIT, :action:drain_the_paddle_culvert))",
         {"action:drain_the_paddle_culvert": "drain the paddle culvert"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:fill_the_culvert", "state:culvert_drained"]),
        ("m02", "Vineyard workers must prune the espalier rows every winter.",
         "RULESET(RULE(REQUIRE, :action:prune_the_espalier_rows))",
         {"action:prune_the_espalier_rows": "prune the espalier rows"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:prune_the_standard_vines", "state:rows_frost_hit"]),
        ("m03", "Apiary visitors are prohibited from swinging their arms near the hives.",
         "RULESET(RULE(PROHIBIT, :action:swing_arms_near_hives))",
         {"action:swing_arms_near_hives": "swinging their arms near the hives"},
         [("MODAL", "PROHIBIT", "prohibited from")], [],
         ["action:stand_near_hives", "state:bees_agitated"]),
        ("m04", "Pottery students are free to use the kick wheels at any time.",
         "RULESET(RULE(PERMIT, :action:use_the_kick_wheels))",
         {"action:use_the_kick_wheels": "use the kick wheels"},
         [("MODAL", "PERMIT", "are free to")], [],
         ["action:use_the_electric_wheels", "state:induction_complete"]),
        ("m05", "Shelter volunteers have to disinfect the kennel runs twice daily.",
         "RULESET(RULE(REQUIRE, :action:disinfect_the_kennel_runs))",
         {"action:disinfect_the_kennel_runs": "disinfect the kennel runs"},
         [("MODAL", "REQUIRE", "have to")], [],
         ["action:disinfect_the_cattery", "state:kennels_empty"]),
        ("m06", "Bell ringers may not lean on the tower ropes.",
         "RULESET(RULE(PROHIBIT, :action:lean_on_the_tower_ropes))",
         {"action:lean_on_the_tower_ropes": "lean on the tower ropes"},
         [("MODAL", "PROHIBIT", "may not")], [],
         ["action:pull_the_tower_ropes", "state:ropes_taut"]),
    ]),
    # ---------------------------------------------------------- condition (6)
    ("condition", "controlled", [
        ("c01", "If the meltwater gauge shows amber, hut wardens must rope the lower bridge.",
         "RULESET(RULE(REQUIRE, :action:rope_the_lower_bridge, WHEN(:state:meltwater_gauge_amber)))",
         {"action:rope_the_lower_bridge": "rope the lower bridge",
          "state:meltwater_gauge_amber": "the meltwater gauge shows amber"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "If")], [],
         ["state:meltwater_gauge_red", "action:rope_the_upper_bridge"]),
        ("c02", "When the curd knife passes the clean-break test, cheesemakers may cut the batch.",
         "RULESET(RULE(PERMIT, :action:cut_the_batch, WHEN(:state:clean_break_test_passed)))",
         {"action:cut_the_batch": "cut the batch",
          "state:clean_break_test_passed": "the curd knife passes the clean-break test"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "When")], [],
         ["state:clean_break_test_failed", "action:stir_the_batch"]),
        ("c03", "Provided the swing bridge is locked, cyclists may cross the cut.",
         "RULESET(RULE(PERMIT, :action:cross_the_cut, WHEN(:state:swing_bridge_locked)))",
         {"action:cross_the_cut": "cross the cut",
          "state:swing_bridge_locked": "the swing bridge is locked"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "Provided")], [],
         ["state:swing_bridge_open", "action:portage_the_cut"]),
        ("c04", "If the moth trap lamp is charging, surveyors must log by torchlight.",
         "RULESET(RULE(REQUIRE, :action:log_by_torchlight, WHEN(:state:moth_lamp_charging)))",
         {"action:log_by_torchlight": "log by torchlight",
          "state:moth_lamp_charging": "the moth trap lamp is charging"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "If")], [],
         ["state:moth_lamp_dark", "action:log_by_lamp"]),
        ("c05", "Whenever the funicular cable groans under load, attendants must halt boarding.",
         "RULESET(RULE(REQUIRE, :action:halt_boarding, WHEN(:state:cable_groans_under_load)))",
         {"action:halt_boarding": "halt boarding",
          "state:cable_groans_under_load": "the funicular cable groans under load"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "Whenever")], [],
         ["state:cable_silent", "action:resume_boarding"]),
        ("c06", "When the curling ice is freshly pebbled, sweepers may not walk the sheet.",
         "RULESET(RULE(PROHIBIT, :action:walk_the_sheet, WHEN(:state:ice_freshly_pebbled)))",
         {"action:walk_the_sheet": "walk the sheet",
          "state:ice_freshly_pebbled": "the curling ice is freshly pebbled"},
         [("MODAL", "PROHIBIT", "may not"), ("RELATION", "IF", "When")], [],
         ["state:ice_worn", "action:sweep_the_sheet"]),
    ]),
    # ---------------------------------------------------------- exception (6)
    ("exception", "controlled", [
        ("e01", "Sawmill staff must wear cut gloves at the bench, except during tool changes.",
         "RULESET(RULE(REQUIRE, :action:wear_cut_gloves_at_bench, EXCEPT(:state:tool_change_in_progress)))",
         {"action:wear_cut_gloves_at_bench": "wear cut gloves at the bench",
          "state:tool_change_in_progress": "during tool changes"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "UNLESS", "except during")], [],
         ["state:blade_guard_removed", "action:wear_cut_gloves_at_store"]),
        ("e02", "Aviary keepers may not enter the netted flight, save when the vet is present.",
         "RULESET(RULE(PROHIBIT, :action:enter_the_netted_flight, EXCEPT(:state:vet_present)))",
         {"action:enter_the_netted_flight": "enter the netted flight",
          "state:vet_present": "the vet is present"},
         [("MODAL", "PROHIBIT", "may not"), ("RELATION", "UNLESS", "save when")], [],
         ["state:keeper_inducted", "action:feed_the_birds"]),
        ("e03", "Maze guides may trim the hedge walls, unless the sprinklers are running.",
         "RULESET(RULE(PERMIT, :action:trim_the_hedge_walls, EXCEPT(:state:sprinklers_running)))",
         {"action:trim_the_hedge_walls": "trim the hedge walls",
          "state:sprinklers_running": "the sprinklers are running"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "UNLESS", "unless")], [],
         ["state:hedge_wet", "action:water_the_hedge"]),
        ("e04", "Quarry drivers must reverse with a banksman, except inside the weighbridge bay.",
         "RULESET(RULE(REQUIRE, :action:reverse_with_banksman, EXCEPT(:state:inside_weighbridge_bay)))",
         {"action:reverse_with_banksman": "reverse with a banksman",
          "state:inside_weighbridge_bay": "inside the weighbridge bay"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "UNLESS", "except inside")], [],
         ["state:banksman_absent", "action:reverse_with_camera"]),
        ("e05", "Boathouse members may not store private shells on the top rack, apart from regatta weeks.",
         "RULESET(RULE(PROHIBIT, :action:store_private_shells_top_rack, EXCEPT(:state:regatta_week)))",
         {"action:store_private_shells_top_rack": "store private shells on the top rack",
          "state:regatta_week": "regatta weeks"},
         [("MODAL", "PROHIBIT", "may not"), ("RELATION", "UNLESS", "apart from")], [],
         ["state:top_rack_full", "action:store_club_shells"]),
        ("e06", "Millers must keep the sluice gates clear of debris, except when the wheel is stopped.",
         "RULESET(RULE(REQUIRE, :action:keep_sluice_gates_clear, EXCEPT(:state:water_wheel_stopped)))",
         {"action:keep_sluice_gates_clear": "keep the sluice gates clear of debris",
          "state:water_wheel_stopped": "the wheel is stopped"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "UNLESS", "except when")], [],
         ["state:debris_light", "action:open_the_sluice_gates"]),
    ]),
    # ----------------------------------------------------------- negation (5)
    ("negation", "controlled", [
        ("n01", "Provided the resin bath does not read hot, printers may mix the fresh batch.",
         "RULESET(RULE(PERMIT, :action:mix_the_fresh_batch, WHEN(NOT(:state:resin_bath_hot))))",
         {"action:mix_the_fresh_batch": "mix the fresh batch",
          "state:resin_bath_hot": "the resin bath does not read hot"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "Provided")], [],
         ["state:resin_bath_cold", "action:stir_the_old_batch"]),
        ("n02", "Lavender pickers must start at dawn if no dew is on the rows.",
         "RULESET(RULE(REQUIRE, :action:start_picking_at_dawn, WHEN(NOT(:state:dew_on_rows))))",
         {"action:start_picking_at_dawn": "start at dawn",
          "state:dew_on_rows": "no dew is on the rows"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "if")], [],
         ["state:rows_irrigated", "action:start_picking_at_noon"]),
        ("n03", "When the ice resurfacer is not in the shed, rink guards must post the caution board.",
         "RULESET(RULE(REQUIRE, :action:post_the_caution_board, WHEN(NOT(:state:resurfacer_in_shed))))",
         {"action:post_the_caution_board": "post the caution board",
          "state:resurfacer_in_shed": "the ice resurfacer is not in the shed"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "When")], [],
         ["state:resurfacer_on_ice", "action:remove_the_caution_board"]),
        ("n04", "Dredger crews may moor at the downstream buoy while the hopper is not full.",
         "RULESET(RULE(PERMIT, :action:moor_at_downstream_buoy, WHEN(NOT(:state:hopper_full))))",
         {"action:moor_at_downstream_buoy": "moor at the downstream buoy",
          "state:hopper_full": "the hopper is not full"},
         [("MODAL", "PERMIT", "may"), ("RELATION", "IF", "while")], [],
         ["state:hopper_empty", "action:moor_at_upstream_buoy"]),
        ("n05", "Caving instructors must rig the second pitch if the ladder is not fixed.",
         "RULESET(RULE(REQUIRE, :action:rig_the_second_pitch, WHEN(NOT(:state:ladder_fixed))))",
         {"action:rig_the_second_pitch": "rig the second pitch",
          "state:ladder_fixed": "the ladder is not fixed"},
         [("MODAL", "REQUIRE", "must"), ("RELATION", "IF", "if")], [],
         ["state:ladder_bolted", "action:rig_the_first_pitch"]),
    ]),
    # --------------------------------------------------------- multiclause (7)
    ("multiclause", "controlled", [
        ("mc01", "Kiln room assistants must stack the biscuit shelves and log the firing card.",
         "RULESET(RULE(REQUIRE, :action:stack_the_biscuit_shelves), RULE(REQUIRE, :action:log_the_firing_card))",
         {"action:stack_the_biscuit_shelves": "stack the biscuit shelves",
          "action:log_the_firing_card": "log the firing card"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:stack_the_glaze_shelves", "action:log_the_clay_card"]),
        ("mc02", "Orchard helpers may gather windfalls and press the morning cider.",
         "RULESET(RULE(PERMIT, :action:gather_windfalls), RULE(PERMIT, :action:press_the_morning_cider))",
         {"action:gather_windfalls": "gather windfalls",
          "action:press_the_morning_cider": "press the morning cider"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:gather_picked_fruit", "action:press_the_evening_cider"]),
        ("mc03", "Riders may not eat on the standing platform or drop litter from the cabins.",
         "RULESET(RULE(PROHIBIT, :action:eat_on_standing_platform), RULE(PROHIBIT, :action:drop_litter_from_cabins))",
         {"action:eat_on_standing_platform": "eat on the standing platform",
          "action:drop_litter_from_cabins": "drop litter from the cabins"},
         [("MODAL", "PROHIBIT", "may not")], [],
         ["action:drink_on_platform", "action:drop_litter_from_platform"]),
        ("mc04", "Depot cleaners must sweep the tram steps and polish the destination glass.",
         "RULESET(RULE(REQUIRE, :action:sweep_the_tram_steps), RULE(REQUIRE, :action:polish_the_destination_glass))",
         {"action:sweep_the_tram_steps": "sweep the tram steps",
          "action:polish_the_destination_glass": "polish the destination glass"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:sweep_the_pit", "action:polish_the_fare_box"]),
        ("mc05", "Bothy keepers may collect peat from the east bank and cut kindling at the shed.",
         "RULESET(RULE(PERMIT, :action:collect_peat_east_bank), RULE(PERMIT, :action:cut_kindling_at_shed))",
         {"action:collect_peat_east_bank": "collect peat from the east bank",
          "action:cut_kindling_at_shed": "cut kindling at the shed"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:collect_peat_west_bank", "action:cut_kindling_at_bothy"]),
        ("mc06", "Judges must check the tatami seams and inspect every foot guard.",
         "RULESET(RULE(REQUIRE, :action:check_the_tatami_seams), RULE(REQUIRE, :action:inspect_every_foot_guard))",
         {"action:check_the_tatami_seams": "check the tatami seams",
          "action:inspect_every_foot_guard": "inspect every foot guard"},
         [("MODAL", "REQUIRE", "must")], [],
         ["action:check_the_mat_edges", "action:inspect_every_gi"]),
        ("mc07", "Pontoon crew may cast the depth lead and read the tide board aloud.",
         "RULESET(RULE(PERMIT, :action:cast_the_depth_lead), RULE(PERMIT, :action:read_the_tide_board_aloud))",
         {"action:cast_the_depth_lead": "cast the depth lead",
          "action:read_the_tide_board_aloud": "read the tide board aloud"},
         [("MODAL", "PERMIT", "may")], [],
         ["action:cast_the_sounder", "action:read_the_wind_gauge"]),
    ]),
    # ------------------------------------------------- per_clause_modality (7)
    ("per_clause_modality", "controlled", [
        ("pm01", "Hut wardens must bank the stove at night and may burn spare kindling at dawn.",
         "RULESET(RULE(REQUIRE, :action:bank_the_stove_at_night), RULE(PERMIT, :action:burn_spare_kindling_at_dawn))",
         {"action:bank_the_stove_at_night": "bank the stove at night",
          "action:burn_spare_kindling_at_dawn": "burn spare kindling at dawn"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may")], [],
         ["action:bank_the_stove_at_dawn", "action:burn_green_wood"]),
        ("pm02", "Grapes may be tread in the stone vat, but presses must be hosed after each run.",
         "RULESET(RULE(PERMIT, :action:tread_grapes_in_stone_vat), RULE(REQUIRE, :action:hose_the_presses))",
         {"action:tread_grapes_in_stone_vat": "tread in the stone vat",
          "action:hose_the_presses": "presses must be hosed"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must")], [],
         ["action:tread_grapes_in_steel_vat", "action:hose_the_vat"]),
        ("pm03", "Smokers must not light up near the hay barn, yet they may use the sheltered porch.",
         "RULESET(RULE(PROHIBIT, :action:smoke_near_hay_barn), RULE(PERMIT, :action:use_sheltered_porch))",
         {"action:smoke_near_hay_barn": "light up near the hay barn",
          "action:use_sheltered_porch": "use the sheltered porch"},
         [("MODAL", "PROHIBIT", "must not"), ("MODAL", "PERMIT", "may")], [],
         ["action:vape_near_hay_barn", "action:use_the_yard_bench"]),
        ("pm04", "Divers must log their bottom time and may borrow the deco slates.",
         "RULESET(RULE(REQUIRE, :action:log_bottom_time), RULE(PERMIT, :action:borrow_the_deco_slates))",
         {"action:log_bottom_time": "log their bottom time",
          "action:borrow_the_deco_slates": "borrow the deco slates"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may")], [],
         ["action:log_surface_time", "action:borrow_the_dive_knives"]),
        ("pm05", "Wool sorters may grade the fleece on the slatted table but must not stack wet bales.",
         "RULESET(RULE(PERMIT, :action:grade_fleece_on_slatted_table), RULE(PROHIBIT, :action:stack_wet_bales))",
         {"action:grade_fleece_on_slatted_table": "grade the fleece on the slatted table",
          "action:stack_wet_bales": "stack wet bales"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PROHIBIT", "must not")], [],
         ["action:grade_fleece_on_floor", "action:stack_dry_bales"]),
        ("pm06", "Saddlers must wax the tack daily and may fit new stirrups on request.",
         "RULESET(RULE(REQUIRE, :action:wax_the_tack), RULE(PERMIT, :action:fit_new_stirrups))",
         {"action:wax_the_tack": "wax the tack",
          "action:fit_new_stirrups": "fit new stirrups"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may")], [],
         ["action:oil_the_tack", "action:fit_new_girths"]),
        ("pm07", "Aquarium staff may record the feeds from the gallery, though flash photography is forbidden at the shark lagoon.",
         "RULESET(RULE(PERMIT, :action:record_feeds_from_gallery), RULE(PROHIBIT, :action:use_flash_at_shark_lagoon))",
         {"action:record_feeds_from_gallery": "record the feeds from the gallery",
          "action:use_flash_at_shark_lagoon": "flash photography"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "PROHIBIT", "forbidden")], [],
         ["action:record_feeds_from_tunnel", "action:use_lamps_at_lagoon"]),
    ]),
    # ---------------------------------------------------- per_clause_actor (6)
    ("per_clause_actor", "controlled", [
        ("pa01", "Grooms may polish the harness, and farriers must trim the rescue ponies.",
         "RULESET(RULE(PERMIT, :action:polish_the_harness, ACTOR(:actor:groom)), RULE(REQUIRE, :action:trim_the_rescue_ponies, ACTOR(:actor:farrier)))",
         {"action:polish_the_harness": "polish the harness",
          "actor:groom": "Grooms", "action:trim_the_rescue_ponies": "trim the rescue ponies",
          "actor:farrier": "farriers"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must")], [],
         ["actor:stable_hand", "action:polish_the_saddle"]),
        ("pa02", "Only the head gardener may divide the tree peonies; volunteers must deadhead the borders.",
         "RULESET(RULE(PERMIT, :action:divide_the_tree_peonies, ONLY_ACTOR(:actor:head_gardener)), RULE(REQUIRE, :action:deadhead_the_borders, ACTOR(:actor:volunteer)))",
         {"action:divide_the_tree_peonies": "divide the tree peonies",
          "actor:head_gardener": "the head gardener",
          "action:deadhead_the_borders": "deadhead the borders",
          "actor:volunteer": "volunteers"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must"),
          ("RELATION", "ONLY_IF", "Only")], [],
         ["actor:trainee_gardener", "action:divide_the_hostas"]),
        ("pa03", "Bakers may sample the levain, and managers must countersign the wastage sheet.",
         "RULESET(RULE(PERMIT, :action:sample_the_levain, ACTOR(:actor:baker)), RULE(REQUIRE, :action:countersign_wastage_sheet, ACTOR(:actor:manager)))",
         {"action:sample_the_levain": "sample the levain",
          "actor:baker": "Bakers",
          "action:countersign_wastage_sheet": "countersign the wastage sheet",
          "actor:manager": "managers"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must")], [],
         ["actor:apprentice_baker", "action:sample_the_dough"]),
        ("pa04", "Trainee smiths must quench the blanks, and only the master smith may open the forge door.",
         "RULESET(RULE(REQUIRE, :action:quench_the_blanks, ACTOR(:actor:trainee_smith)), RULE(PERMIT, :action:open_the_forge_door, ONLY_ACTOR(:actor:master_smith)))",
         {"action:quench_the_blanks": "quench the blanks",
          "actor:trainee_smith": "Trainee smiths",
          "action:open_the_forge_door": "open the forge door",
          "actor:master_smith": "the master smith"},
         [("MODAL", "REQUIRE", "must"), ("MODAL", "PERMIT", "may"),
          ("RELATION", "ONLY_IF", "only the")], [],
         ["actor:journeyman_smith", "action:quench_the_tongs"]),
        ("pa05", "Rowers may adjust the riggers, and coxswains must call the bridge arch.",
         "RULESET(RULE(PERMIT, :action:adjust_the_riggers, ACTOR(:actor:rower)), RULE(REQUIRE, :action:call_the_bridge_arch, ACTOR(:actor:coxswain)))",
         {"action:adjust_the_riggers": "adjust the riggers",
          "actor:rower": "Rowers",
          "action:call_the_bridge_arch": "call the bridge arch",
          "actor:coxswain": "coxswains"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must")], [],
         ["actor:coach", "action:adjust_the_footplates"]),
        ("pa06", "Lighthouse keepers may wind the mechanism, and engineers must seal the lamp room.",
         "RULESET(RULE(PERMIT, :action:wind_the_mechanism, ACTOR(:actor:lighthouse_keeper)), RULE(REQUIRE, :action:seal_the_lamp_room, ACTOR(:actor:engineer)))",
         {"action:wind_the_mechanism": "wind the mechanism",
          "actor:lighthouse_keeper": "Lighthouse keepers",
          "action:seal_the_lamp_room": "seal the lamp room",
          "actor:engineer": "engineers"},
         [("MODAL", "PERMIT", "may"), ("MODAL", "REQUIRE", "must")], [],
         ["actor:relief_keeper", "action:wind_the_winch"]),
    ]),
]
