"""Gold-free P1/native prediction and controlled post-seal policy-world scoring."""

from collections import Counter
from dataclasses import asdict

from guardian_truth.cycle2.policy_arms import model_policy_proposal
from guardian_truth.cycle2.policy_semantics import score_policy_program
from .policy_programs_v2 import parse_policy_programs


METRIC_RULES = {
    'role': 'Policy Semantics V2 observed development regression; never blind evidence',
    'baseline': 'exact frozen Cycle2 P1 system/messages/schema/validation/effort; no P2 arm; common new transport envelope declared separately',
    'candidate_behavior': 'all official closed benchmark worlds; all/any candidate correctness, no confidence selection',
    'transport_schema': 'field/component failures excluded from conditional semantic denominators and retained operationally',
    'coverage': 'no authoritative whole-policy universe supplied; finite atom catalog/challenger does not close NL',
    'full_interpretation_recall': 'not established: benchmark does not enumerate all reasonable NL readings',
    'core': 'no whole-Core verdict/certificate generated by this meaning-stage benchmark',
}


def predict_policy_programs(blind_case, backend, wire_client, contract):
    native = parse_policy_programs(blind_case.policy, blind_case.atom_catalog, backend)
    p1 = model_policy_proposal(wire_client, blind_case, 'P1', contract)
    return {'native': asdict(native), 'fixed_p1': p1}


def score_program_case(case, prediction):
    parsed, p1 = prediction['native'], prediction['fixed_p1']
    native_rows = [score_policy_program(case, {name: [list(clause) for clause in hypothesis['program'][name]]
        for name in ('violation_clauses', 'permission_clauses')}) for hypothesis in parsed['hypotheses']]
    p1_row = score_policy_program(case, p1['prediction']['program']) if p1['schema_status'] == 'VALID' else None
    correct = sum(row['behavioral_semantic_correct'] for row in native_rows)
    components = set()
    for _, reason in parsed['failures']:
        components.add('TRANSPORT' if reason == 'TRANSPORT_ERROR' else 'SCHEMA' if reason == 'SCHEMA_ERROR' else 'POLICY_GENERATION')
    if parsed['coverage']['status'] == 'OPEN_SEMANTICS':
        components.add('POLICY_COVERAGE')
    if any(not row['behavioral_semantic_correct'] for row in native_rows):
        components.add('POLICY_GENERATION')
    if p1['transport_status'] != 'SUCCESS':
        components.add('TRANSPORT')
    elif p1['schema_status'] != 'VALID':
        components.add('SCHEMA')
    return {'case_id': case.id, 'family': case.family,
        'candidate_count': len(native_rows), 'candidate_correct': correct,
        'candidate_world_results': native_rows, 'any_candidate_correct': correct > 0,
        'all_candidate_correct': bool(native_rows) and correct == len(native_rows),
        'native_full_schema_transport_eligible': not parsed['failures'],
        'native_operationally_correct': not parsed['failures'] and bool(native_rows) and correct == len(native_rows),
        'p1': p1_row, 'p1_schema_status': p1['schema_status'], 'p1_transport_status': p1['transport_status'],
        'coverage': parsed['coverage']['status'], 'unresolved_terms': list(parsed['coverage']['unresolved_terms']),
        'discarded_hypotheses': [list(item) for item in parsed['coverage']['discarded_hypotheses']], 'components': sorted(components)}


def summarize_programs(cases, rows):
    by_id = {row['case_id']: row for row in rows}
    if len(by_id) != len(rows) or set(by_id) != {case.id for case in cases}:
        raise ValueError('exact complete unique regression case coverage required')
    scores = [score_program_case(case, by_id[case.id]['prediction']) for case in cases]
    candidate_count = sum(row['candidate_count'] for row in scores)
    candidate_correct = sum(row['candidate_correct'] for row in scores)
    valid_p1 = [row for row in scores if row['p1'] is not None]
    native_eligible = [row for row in scores if row['native_full_schema_transport_eligible'] and row['candidate_count']]
    paired = [row for row in native_eligible if row['p1'] is not None]
    return {'case_count': len(cases), 'candidate_behavior': {'correct': candidate_correct, 'candidates': candidate_count,
        'accuracy_on_accepted_candidates': candidate_correct / candidate_count if candidate_count else None,
        'full_case_eligible': len(native_eligible),
        'all_candidate_case_accuracy': sum(row['all_candidate_correct'] for row in native_eligible) / len(native_eligible) if native_eligible else None,
        'any_candidate_case_accuracy': sum(row['any_candidate_correct'] for row in native_eligible) / len(native_eligible) if native_eligible else None,
        'strict_operational_all_correct_yield': sum(row['native_operationally_correct'] for row in scores) / len(scores)},
        'fixed_p1_behavior': {'eligible': len(valid_p1), 'correct': sum(row['p1']['behavioral_semantic_correct'] for row in valid_p1),
            'accuracy': sum(row['p1']['behavioral_semantic_correct'] for row in valid_p1) / len(valid_p1) if valid_p1 else None},
        'paired': {'n': len(paired), 'native_minus_p1_all_candidate_correct':
            sum(int(row['all_candidate_correct']) - int(row['p1']['behavioral_semantic_correct']) for row in paired) / len(paired) if paired else None},
        'semantic_coverage': dict(Counter(row['coverage'] for row in scores)),
        'full_interpretation_recall': 'NOT_ESTABLISHED_NO_EXHAUSTIVE_NL_READING_GOLD',
        'unsupported_interpretation_rate': 'NOT_ESTABLISHED_WRONG_WORLD_BEHAVIOR_IS_NOT_REASONABLENESS_ADJUDICATION',
        'whole_core_gain': 'NOT_ESTABLISHED_POLICY_MEANING_STAGE_ONLY', 'failure_taxonomy': scores,
        'blind_cases_read': 0}
